// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUI_h
#define GUI_h
#include <FL/Fl.H>
#include "SpectreDrawer.h"
#include "GUI_event_handler.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *tabs_center_freq_field;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *tabs_sample_rate_field;
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
extern Fl_Output *sdr_device_name_field;
extern Fl_Output *tuner_name_field;
extern Fl_Value_Output *tuner_gain_field;
#include <FL/Fl_Check_Button.H>
extern Fl_Value_Input *freq_hop_step_field;
extern Fl_Value_Input *hop_steps_field;
extern Fl_Value_Input *hop_bandwidth_field;
extern Fl_Value_Input *hop_period_field;
extern SpectreDrawer *spectre_box;
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Button.H>
extern Fl_Value_Input *center_freq_field;
#include <FL/Fl_Counter.H>
extern Fl_Counter *center_freq_toggle;
#include <FL/Fl_Tree.H>
extern Fl_Tree *layers_tree;
#include <FL/Fl_Text_Display.H>
extern Fl_Output *layer_name_field;
extern Fl_Output *layer_input_type_field;
extern Fl_Output *layer_output_type_field;
extern Fl_Value_Output *layer_output_buffer_size;
extern Fl_Value_Output *layer_sample_rate;
extern Fl_Value_Output *layer_input_buffer_size;
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_hfgdhf[];
void update_center_freq_kHz(int freq);
void update_bandwidth_kHz(int freq);
Fl_Double_Window* make_about_window();
#include <FL/Fl_Input_Choice.H>
extern Fl_Input_Choice *new_layer_type_choice;
#include <FL/Fl_Choice.H>
extern Fl_Choice *new_layer_parent_choice;
Fl_Double_Window* make_layer_creation_window();
#endif
